# Generated by Django 3.2.3 on 2021-05-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='You',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_Name', models.CharField(max_length=100)),
                ('your_Major', models.CharField(max_length=200)),
                ('your_MBTI', models.CharField(max_length=100)),
            ],
        ),
    ]
