# Generated by Django 3.2.3 on 2021-05-13 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='you',
            name='your_Favorite',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='you',
            name='your_MBTI',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='you',
            name='your_Major',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='you',
            name='your_Name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
