# Generated by Django 3.2.3 on 2021-05-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0002_auto_20210513_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='you',
            name='your_Age',
            field=models.IntegerField(default=0),
        ),
    ]
